.PHONY: check-echo-dep check-cat-dep check-python-dep all

all: check-echo-dep check-cat-dep check-python-dep


check-echo-dep:
	ldd /bin/echo


check-cat-dep:
	ldd /bin/cat


check-python-dep:
	ldd /usr/bin/python3
